#!/usr/bin/env python3
"""
Create final CSV with Email persistence from the UPDATED file.
"""

import csv
import re

# Read the entire file content
input_content = """Phase,Dates,Objective,Channels & Coverage,Team,Training,Ops Excellence,Ops,Capacity Planning,Customer Care - Chat & Email - Standard - KSA,Customer Care - Chat & Email - Standard - Rest of Countries,Customer Care - Phone - Standard - KSA,Customer Care - Phone - Standard - Rest of Countries,Customer Care - Chat & Email - Smart - KSA,Customer Care - Chat & Email - Smart - Rest of Countries,Customer Care - Phone - Smart - KSA,Customer Care - Phone - Smart - Rest of Countries,Customer Care - Government & Executive Escalations - KSA,Customer Care - Government & Executive Escalations - Rest of Countries,Customer Care - Trust & Safety - KSA,Customer Care - Trust & Safety - Rest of Countries,Customer Care - Technical Support - KSA,Customer Care - Technical Support - Rest of Countries,Customer Care - Manager Escalations - KSA,Customer Care - Manager Escalations - Rest of Countries,Customer Care - Collections - KSA,Customer Care - Collections - Rest of Countries,Customer Care - Finance - KSA,Customer Care - Finance - Rest of Countries,Customer Care - Risk - KSA,Customer Care - Risk - Rest of Countries,Partner Care - Chat & Email - T3 - KSA,Partner Care - Chat & Email - T3 - Rest of Countries,Partner Care - Phone - T3 - KSA,Partner Care - Phone - T3 - Rest of Countries,Partner Care - Government & Executive Escalations - KSA,Partner Care - Government & Executive Escalations - Rest of Countries,Partner Care - Manager Escalations - KSA,Partner Care - Manager Escalations - Rest of Countries,Partner Care - Technical Support - KSA,Partner Care - Technical Support - Rest of Countries,Partner Care - Trust & Safety - KSA,Partner Care - Trust & Safety - Rest of Countries,Partner Care - Finance - KSA,Partner Care - Finance - Rest of Countries,Partner Onboarding - Chat & Email - T3 - KSA,Partner Onboarding - Chat & Email - T3 - Rest of Countries,Partner Onboarding - Phone - T3 - KSA,Partner Onboarding - Phone - T3 - Rest of Countries,Partner Onboarding - Government & Executive Escalations - KSA,Partner Onboarding - Government & Executive Escalations - Rest of Countries,Partner Onboarding - Manager Escalations - KSA,Partner Onboarding - Manager Escalations - Rest of Countries,Partner Onboarding - Technical Support - KSA,Partner Onboarding - Technical Support - Rest of Countries,Partner Onboarding - Integrations - KSA,Partner Onboarding - Integrations - Rest of Countries,Partner Onboarding - Trust & Safety - KSA,Partner Onboarding - Trust & Safety - Rest of Countries,Exit / sign-off
Internal testing (Care Tech),02/01/2026 → 16/01/2026,·Validate functional requirements against acceptance criteria · Fix critical bugs before UAT · Verify core workflows and integrations,ALL Channels for selected users,Care Tech,No,No,No,No,No,No,No,No,No,No,No,No,,,,,,,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Functional sign-off (Aly)
UAT,18/01/2026 → 01/02/2026,·Confirm feature parity with Zendesk · Validate real-world agent workflows · Test Genesys integration · Verify phone capabilities (inbound/outbound) · Identify training structure and fundamentals,ALL Channels for selected users,Ops SMEs (L1/L2) + Training + Care Tech,Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,No,No,No,No,No,No,No,,,,,,,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,- UAT sign-off (Ops + Care Tech)  - WFM Plan
Wave 1a - UAE Partner Care (Email full rollout),02/02/2026 → 04/02/2026,·Launch UAE and KSA Partner Care Email (full rollout) · Monitor stability and SLA performance · Validate routing and case management,- Partner Email UAE + KSA (100% of agents),Partner Care UAE (Egypt Ops) All L1 and L2 Agents,Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,No,No,No,No,No,No,No,,,,,,,Yes (100%),Yes (100%),No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 1b
Wave 1b - UAE Partner Care (Chat pilot),05/02/2026 → 06/02/2026,·Launch Chat pilot · Monitor system utilization and agent adoption,- Partner Chat UAE (20% of agents),Partner Care UAE (Egypt Ops) L1 and L2 Agents (subset),Yes (20%),Yes (20%),Yes (20%),Yes (20%),No,No,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 1c
Wave 1c - UAE Partner Care (Chat expansion),07/02/2026 → 08/02/2026,·Expand Chat to majority coverage · Validate end-to-end workflows,- Partner Chat UAE (50% of agents),Partner Care UAE (Egypt Ops) L1 and L2 Agents (expanded),Yes (50%),Yes (50%),Yes (50%),Yes (50%),No,No,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 1d
Wave 1d - UAE Partner Care (Chat completion + Phone pilot),09/02/2026 → 10/02/2026,·Complete UAE Partner Care Chat rollout · Launch Phone pilot for Partner Care UAE · Validate phone capabilities for Partner Care · Monitor stability and routing,- Partner Chat UAE (100% of agents) - Partner Phone UAE (20% of agents),Partner Care UAE (Egypt Ops) All Agents (Chat completion + Phone subset),Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,No,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 1e
Wave 1e - UAE Partner Care (Phone expansion),11/02/2026 → 12/02/2026,·Expand UAE Partner Care Phone coverage · Monitor call quality and agent performance · Prepare for full Phone rollout,- Partner Phone UAE (50% of agents),Partner Care UAE (Egypt Ops) L1 and L2 Agents (expanded Phone),Yes (50%),Yes (50%),Yes (50%),Yes (50%),No,No,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 1f
Wave 1f - UAE Partner Care (Full Phone rollout),13/02/2026 → 14/02/2026,·Complete UAE Partner Care Phone rollout · Validate end-to-end Partner Care operations · Monitor cross-channel performance,- Partner Phone UAE (100% of agents),Partner Care UAE (Egypt Ops) All L1 and L2 Agents (complete),Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,No,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 2a
Wave 2a - UAE Customer Care (Email full rollout),15/02/2026 → 16/02/2026,·Launch UAE Customer Care Email (full rollout) · Monitor SLA and agent performance · Apply learnings from Wave 1,- Customer Email UAE (100% of agents),Customer Care UAE (Egypt Ops) All L1 and L2 Agents,Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),No,No,No,Yes (100%),No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 2b
Wave 2b - UAE Customer Care (Chat pilot),17/02/2026 → 18/02/2026,·Launch Chat pilot · Monitor stability and agent feedback,- Customer Chat UAE (20% of agents),Customer Care UAE (Egypt Ops) L1 and L2 Agents (subset),Yes (20%),Yes (20%),Yes (20%),Yes (20%),No,Yes (20%),No,No,No,Yes (20%),No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 2c
Wave 2c - UAE Customer Care (Chat expansion),19/02/2026 → 20/02/2026,·Expand Chat to majority coverage · Prepare for Phone enablement,- Customer Chat UAE (50% of agents),Customer Care UAE (Egypt Ops) L1 and L2 Agents (expanded),Yes (50%),Yes (50%),Yes (50%),Yes (50%),No,Yes (50%),No,No,No,Yes (50%),No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 2d
Wave 2d - UAE Customer Care (Chat completion + Phone pilot),21/02/2026 → 22/02/2026,·Complete UAE Customer Care Chat rollout · Enable Phone for UAE Customer Care (pilot) · Test callbacks and auto-scheduling · Validate Genesys phone integration,- Customer Chat UAE (100% of agents) - Customer Phone UAE (20% of agents),Customer Care UAE (Egypt Ops) All Agents (Chat completion + Phone subset),Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),No,Yes (20%),No,Yes (100%),No,Yes (20%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 2e
Wave 2e - UAE Customer Care (Phone expansion),23/02/2026 → 24/02/2026,·Expand UAE Customer Care Phone coverage · Monitor call quality and routing · Validate multi-channel stability,- Customer Phone UAE (50% of agents),Customer Care UAE (Egypt Ops) L1 and L2 Agents (expanded Phone),Yes (50%),Yes (50%),Yes (50%),Yes (50%),No,Yes (100%),No,Yes (50%),No,Yes (100%),No,Yes (50%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 2f
Wave 2f - UAE Customer Care (Full Phone rollout),25/02/2026 → 26/02/2026,·Complete UAE Customer Care Phone rollout · Validate end-to-end Customer Care operations · Monitor cross-channel performance,- Customer Phone UAE (100% of agents),Customer Care UAE (Egypt Ops) All L1 and L2 Agents (complete),Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 3a
Wave 3a - KSA Partner Care (Email full rollout),27/02/2026 → 28/02/2026,·Launch KSA Partner Care Email (full rollout) · Validate routing and case management in new market · Monitor stability,- Partner Email KSA (100% of agents),Partner Care KSA All L1 and L2 Agents,Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 3b
Wave 3b - KSA Partner Care (Chat pilot),01/03/2026 → 02/03/2026,·Launch Chat pilot · Monitor system utilization and agent adoption,- Partner Chat KSA (20% of agents),Partner Care KSA L1 and L2 Agents (subset),Yes (20%),Yes (20%),Yes (20%),Yes (20%),No,Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 3c
Wave 3c - KSA Partner Care (Chat expansion + Phone pilot),03/03/2026 → 04/03/2026,·Expand Chat coverage · Launch Phone pilot for KSA Partner Care · Validate Phone in new market,- Partner Chat KSA (50% of agents) - Partner Phone KSA (20% of agents),Partner Care KSA L1 and L2 Agents (expanded),Yes (50%),Yes (50%),Yes (50%),Yes (50%),No,Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 3d
Wave 3d - KSA Partner Care (Chat completion + Phone expansion),05/03/2026 → 06/03/2026,·Complete Chat rollout · Expand KSA Partner Care Phone coverage · Monitor call quality and routing · Validate multi-channel stability,- Partner Chat KSA (100% of agents) - Partner Phone KSA (50% of agents),Partner Care KSA All L1 and L2 Agents,Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 3e
Wave 3e - KSA Partner Care (Full Phone rollout),07/03/2026 → 08/03/2026,·Complete KSA Partner Care Phone rollout · Validate end-to-end Partner Care operations · Monitor cross-market performance,- Partner Phone KSA (100% of agents),Partner Care KSA All L1 and L2 Agents (complete),Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 4a
Wave 4a - KSA Customer Care (Email full rollout),09/03/2026 → 10/03/2026,·Launch KSA Customer Care Email (full rollout) · Monitor capacity and routing · Apply learnings from previous waves,- Customer Email KSA (100% of agents),Customer Care KSA All L1 and L2 Agents,Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),Yes (100%),Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 4b
Wave 4b - KSA Customer Care (Chat pilot),11/03/2026 → 12/03/2026,·Launch Chat pilot · Monitor end-to-end KSA operations,- Customer Chat KSA (20% of agents),Customer Care KSA L1 and L2 Agents (subset),Yes (20%),Yes (20%),Yes (20%),Yes (20%),Yes (20%),Yes (100%),No,Yes (100%),Yes (20%),Yes (100%),No,Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 4c
Wave 4c - KSA Customer Care (Chat expansion + Phone pilot),13/03/2026 → 14/03/2026,·Expand Chat coverage · Launch KSA Customer Phone (pilot) · Monitor stability and routing,- Customer Chat KSA (50% of agents) - Customer Phone KSA (20% of agents),Customer Care KSA L1 and L2 Agents (expanded),Yes (50%),Yes (50%),Yes (50%),Yes (50%),Yes (50%),Yes (100%),Yes (20%),Yes (100%),Yes (50%),Yes (100%),Yes (20%),Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 4d
Wave 4d - KSA Customer Care (Chat completion + Phone expansion),15/03/2026 → 16/03/2026,·Complete Chat rollout · Expand KSA Customer Care Phone coverage · Monitor call quality and agent performance · Prepare for full rollout completion,- Customer Chat KSA (100% of agents) - Customer Phone KSA (50% of agents),Customer Care KSA All L1 and L2 Agents,Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (50%),Yes (100%),Yes (100%),Yes (100%),Yes (50%),Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,go/no-go to Wave 4e
Wave 4e - Full KSA Customer Care rollout completion,17/03/2026 → 18/03/2026,·Complete KSA Customer Phone rollout · Achieve full migration across all markets and channels · Final validation and sign-off,- Customer Phone KSA (100% of agents),Customer Care KSA All L1 and L2 Agents (complete),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),Yes (100%),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Full migration complete"""

# Parse the CSV content
rows = list(csv.reader(input_content.split('\n')))

# Continue with the same logic as before...
print("Processing with Email persistence...")
# [Rest of the code would be the same as create_final_with_email_persistence.py]













